language: php
php: 7.2
script: echo "skipping test"
before_install:
  - openssl aes-256-cbc -K $encrypted_8fa024c173a1_key -iv $encrypted_8fa024c173a1_iv -in deploy_rsa.enc -out ~\/.ssh/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    branch: dev
